[package]
name = "bd-core"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
time = { version = "0.3.36", features = ["formatting"] }
